HotelApplication/Models/RoomType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelApplication.Models
{
    public class RoomType
    {
        public byte Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Size { get; set; }
        public byte TotalAmount { get; set; }
        public byte AvailableAmount { get; set; }
    }
}

HotelApplication/Controllers/API/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using HotelApplication.Models;
using HotelApplication.DTOs;
using AutoMapper;

namespace HotelApplication.Controllers.API
{
    public class CustomersController : ApiController
    {
        private ApplicationDbContext _context;

        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET /api/Services/Customers
        [Route("api/Services/Customers")]
        public IEnumerable<CustomerDTO> GetCustomers()
        {
            return _context.Customers.ToList().Select(Mapper.Map<Customer,CustomerDTO>);
        }

        // GET /api/Services/Customers/1
        [Route("api/Services/Customers/{id}")]
        public CustomerDTO GetCustomer(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            return Mapper.Map<Customer,CustomerDTO>(customer);
        }

        // POST /api/Services/Customers
        [HttpPost]
        [Route("api/Services/Customers")]
        public CustomerDTO CreateCustomer (CustomerDTO customerDTO)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var customer = Mapper.Map<CustomerDTO, Customer>(customerDTO);
            _context.Customers.Add(customer);
            _context.SaveChanges();

            customerDTO.Id = customer.Id;

            return customerDTO;

        }

        // PUT /api/Services/Customers/1
        [HttpPut]
        [Route("api/Services/Customers/{id}")]
        public void UpdateCustomer (int id, CustomerDTO customerDTO)
        {
            var customerInDb = _context.Customers.SingleOrDefault(c=>c.Id==id);

            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            if (customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            Mapper.Map(customerDTO, customerInDb);

            _context.SaveChanges();
        }

        // DELETE /api/Services/Customers/1
        [HttpDelete]
        [Route("api/Services/Customers/{id}")]
        public void DeleteCustomer(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.Customers.Remove(customer);
            _context.SaveChanges();
        }
    }
}

HotelApplication/Controllers/API/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using HotelApplication.Models;
using System.Data.Entity;
using HotelApplication.DTOs;
using AutoMapper;

namespace HotelApplication.Controllers.API
{
    public class ReservationsController : ApiController
    {
        private ApplicationDbContext _context;

        public ReservationsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET /api/Services/Reservations
        [Route("api/Services/Reservations")]
        public IEnumerable<ReservationDTO> GetReservations()
        {
            return _context.Reservations
                .Include(r=>r.Customer)
                .Include(r=>r.Room)
                .Include(r=>r.RStatus)
                .ToList()
                .Select(Mapper.Map<Reservation,ReservationDTO>);

        }

        // GET /api/Services/Reservations/1
        [Route("api/Services/Reservations/{id}")]
        public ReservationDTO GetReservation(int id)
        {
            var reservation = _context.Reservations.SingleOrDefault(r => r.Id == id);

            if(reservation == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            return Mapper.Map<Reservation,ReservationDTO>(reservation);
        }

        // PUT /api/Services/Reservations/1
        [HttpPut]
        [Route("api/Services/Reservations/{id}")]
        public void UpdateReservation(ReservationDTO reservationDTO,int id)
        {
            var reservationInDb = _context.Reservations.SingleOrDefault(r => r.Id == id);

            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            if (reservationInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            Mapper.Map(reservationInDb, reservationDTO);

            _context.SaveChanges();
        }

        // DELETE /api/Services/Reservations/1
        [Route("api/Services/Reservations/{id}")]
        public void DeleteReservation(int id)
        {
            var reservation = _context.Reservations.SingleOrDefault(r => r.Id == id);

            if (reservation == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.Reservations.Remove(reservation);
            _context.SaveChanges();
        }


        // PUT /api/Services/Reservations/Status/1
        [HttpPut]
        [Route("api/Services/Reservations/Cancel/{id},{status}")]
        public void ReservationStatus(int id,string status)
        {
            var reservation = _context.Reservations.SingleOrDefault(r => r.Id == id);

            if (reservation == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            if (status == "confirm")
                reservation.RStatusId = 1;
                        
            else
                reservation.RStatusId = 2;

            _context.SaveChanges();
        }
    }
}

HotelApplication/Controllers/API/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using HotelApplication.Models;
using HotelApplication.DTOs;
using System.Data.Entity;
using AutoMapper;

namespace HotelApplication.Controllers.API
{
    public class RoomsController : ApiController
    {
        private ApplicationDbContext _context;

        public RoomsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET /api/Services/Rooms
        [Route("api/Services/Rooms")]
        public IEnumerable<RoomDTO> GetRooms()
        {
            return _context.Rooms.Include(c=>c.RoomStatus).ToList().Select(Mapper.Map<Room,RoomDTO>);
        }


        // PUT /api/Services/Rooms/1

        [HttpPut]
        [Route("api/Services/Rooms/{id}")]
        public void UpdateRoom(RoomDTO roomDTO,int id)
        {
            var roomInDb = _context.Rooms.SingleOrDefault(r => r.Id == id);

            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            if (roomInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            Mapper.Map(roomDTO, roomInDb);

            _context.SaveChanges();
        }


    }
}

HotelApplication/Controllers/API/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using HotelApplication.Models;
using HotelApplication.DTOs;
using AutoMapper;

namespace HotelApplication.Controllers.API
{
    public class ServicesController : ApiController
    {
        private ApplicationDbContext _context;

        public ServicesController()
        {
            _context = new ApplicationDbContext();
        }

        // GET /api/Services/Customers
        [Route("api/Services/Customers")]
        public IEnumerable<CustomerDTO> GetCustomers()
        {
            return _context.Customers.ToList().Select(Mapper.Map<Customer,CustomerDTO>);
        }

        // GET /api/Services/Customers/1
        [Route("api/Services/Customers/{id}")]
        public CustomerDTO GetCustomer(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            return Mapper.Map<Customer,CustomerDTO>(customer);
        }

        // POST /api/Services/Customers
        [HttpPost]
        [Route("api/Services/Customers")]
        public CustomerDTO CreateCustomer (CustomerDTO customerDTO)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var customer = Mapper.Map<CustomerDTO, Customer>(customerDTO);
            _context.Customers.Add(customer);
            _context.SaveChanges();

            customerDTO.Id = customer.Id;

            return customerDTO;

        }

        // PUT /api/Services/Customers/1
        [HttpPut]
        [Route("api/Services/Customers/{id}")]
        public void UpdateCustomer (int id, CustomerDTO customerDTO)
        {
            var DBcustomer = _context.Customers.SingleOrDefault(c=>c.Id==id);

            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            if (DBcustomer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            Mapper.Map(customerDTO, DBcustomer);

            _context.SaveChanges();
        }

        // DELETE /api/Services/Customers/1
        [HttpDelete]
        [Route("api/Services/Customers/{id}")]
        public void DeleteCustomer(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.Customers.Remove(customer);
            _context.SaveChanges();
        }
    }
}

HotelApplication/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelApplication.Models;
using HotelApplication.ViewModels;
using AutoMapper;
using FluentValidation.Results;

namespace HotelApplication.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext _context;

        public CustomerController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new CustomerFormViewModel
                {
                    Customer = customer,
                    Genders = _context.Genders.ToList()
                };
                return View("NewForm", viewModel);
            }

            _context.Customers.Add(customer);
            _context.SaveChanges();

            return RedirectToAction("Customers", "Service");
        }

        //[HttpPost]
        public ActionResult NewForm()
        {
            var customer = new Customer();
            var room = _context.Rooms.ToList();
            var gender = _context.Genders.ToList();

            var viewModel = new CustomerFormViewModel
            {
                Customer = customer,
                Rooms = room,
                Genders = gender
            };

            return View(viewModel);
        }

       
        //[HttpPut]
        public ActionResult CustomerDetails(int id)
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
                return HttpNotFound();

            var room = _context.Rooms.ToList();
            var gender = _context.Genders.ToList();

            var viewModel = new CustomerFormViewModel
            {
                Customer = customer,
                Rooms = _context.Rooms.ToList(),
                Genders = _context.Genders.ToList()
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            //CustomerValidator validator = new CustomerValidator();

            //ValidationResult results = validator.Validate(customer);

            if (!ModelState.IsValid)
            {

                var viewModel = new CustomerFormViewModel
                {
                    Customer = customer,
                    Genders = _context.Genders.ToList()
                };
                return View("CustomerDetails", viewModel);
            }

            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == customer.Id);

            Mapper.Map(customer, customerInDb);

            _context.SaveChanges();

            return RedirectToAction("Customers","Service");
        }
        
    }
}

HotelApplication/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelApplication.Models;
using HotelApplication.ViewModels;
using System.Data.Entity;
using HotelApplication.Classes;


namespace HotelApplication.Controllers
{
    public class ReservationController : Controller
    {
        private ApplicationDbContext _context;
        private DateChecker _datechecker;

        public ReservationController()
        {
            _datechecker = new DateChecker();
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult NewForm()
        {
            var reservation = new Reservation
            {
                Customer = new Customer(),
                Room = new Room(),
                Genders = _context.Genders.ToList(),
                RoomTypes = _context.RoomTypes.ToList(),
            };

            return View(reservation);
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        public ActionResult Create(Customer customer, Room room, Reservation reserv)
        {


            if (_datechecker.CheckDateAvailability(room, reserv, _context) == null)

                return RedirectToAction("Reservations", "Service");

            var roomInDb = _datechecker.CheckDateAvailability(room, reserv, _context);

            roomInDb.RoomStatusId = 2;

            _context.Customers.Add(customer);
            _context.SaveChanges();

            var reservation = new Reservation
            {
                Customer = _context.Customers.First(c => c.IDNumber == customer.IDNumber),
                Room = roomInDb,
                RStatusId = 3,
                CheckIn = reserv.CheckIn,
                CheckOut = reserv.CheckOut,
                RoomStatusId= 2
            };

            _context.Reservations.Add(reservation);

            _context.SaveChanges();

            return RedirectToAction("Reservations", "Service");
        }

    }
}

HotelApplication/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelApplication.Models;
using HotelApplication.ViewModels;
using AutoMapper;

namespace HotelApplication.Controllers
{
    public class RoomController : Controller
    {
        private ApplicationDbContext _context;

        public RoomController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Rooms
        public ActionResult Index()
        {
            return View();
        }

        //[HttpPut]
        public ActionResult RoomDetails(int id)
        {
            var room = _context.Rooms.SingleOrDefault(c => c.Id == id);

            if (room == null)
                return HttpNotFound();

            var rmStatus = _context.RoomStatus.ToList();
            var rmType = _context.RoomTypes.ToList();

            var viewModel = new RoomFormViewModel
            {
                Room = room,
                RoomTypes = _context.RoomTypes.ToList(),
                RoomStatuses = _context.RoomStatus.ToList(),
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult Edit(Room room)
        {
            
            var roomInDb = _context.Rooms.SingleOrDefault(c => c.Id == room.Id);

            Mapper.Map(room, roomInDb);

            _context.SaveChanges();

            return RedirectToAction("Rooms", "Service");
        }


    }
}

HotelApplication/Views/Service/CustomerDetails.cshtml
@model HotelApplication.ViewModels.CustomerFormViewModel
@{
    ViewBag.Title = "CustomerDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_ServiceNavBar")

<h2>@Model.Customer.FirstName</h2>


@using (Html.BeginForm("Edit", "Service"))
{
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.Gender)
        @Html.DropDownListFor(c => c.Customer.GenderId, new SelectList(Model.Genders, "Id", "Name"), new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.FirstName)
        @Html.TextBoxFor(c => c.Customer.FirstName, new { @class = "form-control" })
        @Html.ValidationMessageFor(c=>c.Customer.FirstName)
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.LastName)
        @Html.TextBoxFor(c => c.Customer.LastName, new { @class = "form-control" })
    </div>
    <div class="form-group input-group-md">
        @Html.LabelFor(c => c.Customer.DateOfBirth)
        @Html.TextBoxFor(c => c.Customer.DateOfBirth, "   {0:d MMM yyyy}", new { @class = "form-control datepicker" })
        @Html.ValidationMessageFor(c => c.Customer.DateOfBirth)
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.IDNumber)
        @Html.TextBoxFor(c => c.Customer.IDNumber, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.PhoneNumber)
        @Html.TextBoxFor(c => c.Customer.PhoneNumber, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.EmailAddress)
        @Html.TextBoxFor(c => c.Customer.EmailAddress, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(c => c.Customer.Id)
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="/Service/Customers" class="btn btn-danger">Cancel</a>



}

@section Scripts{
    <script type="text/javascript">

        $('.datepicker').datepicker();

    </script>

}

HotelApplication/Views/Service/Customers.cshtml
@model HotelApplication.ViewModels.CustomerServiceViewModel
@{
    ViewBag.Title = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_ServiceNavBar")

<h2>Customers</h2>

<hr />
<button onclick="location.href='@Url.Action("NewForm", "Customer")'" class="btn btn-primary">Add Customer</button>
<hr />

<table id="customers" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

@section scripts{
    <script>
        $(document).ready(function () {
           var table =  $("#customers").DataTable({
                ajax: {
                    url: "/api/Services/Customers",
                    dataSrc: "",
                },

                columns: [
                    {
                        data: "firstName"
                    },

                    {
                        data: "lastName"
                    },

                {
                    data: "id",
                    render: function (data, type, customer) {
                        var editBtn = "<a href='/Customer/CustomerDetails/" + data + "' class='btn btn-primary' data-customer-id= >Edit</a>";
                        var deleteBtn = "<button class='btn btn-danger js-delete' data-customer-id=" + data + ">Delete</button>";
                        return editBtn + deleteBtn

                    }
                }

                ]
            });


            $("#customers").on("click", ".js-delete", function () {
                var button = $(this);

                bootbox.confirm("Are you sure you want to delete this customer?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/Services/Customers/" + button.attr("data-customer-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }
                        })
                    }
                });
            });

            //$("#customers").on("click", ".js-edit", function () {
            //    var button = $(this);
            //    bootbox.confirm("Do you want to edit this user?", function (result) {
            //        if (result) {
            //            $.ajax({
            //                url: "/api/Services/Customers/" + button.attr("data-customer-id"),
            //                method: "PUT",
            //                success: function (result) {
            //                    console.log("Success!");
            //                }
            //            })
            //        }
            //    })
            //});
        })
    </script>
}

HotelApplication/Views/Service/NewForm.cshtml
@model HotelApplication.ViewModels.CustomerFormViewModel
@{
    ViewBag.Title = "New Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Customer</h2>

@using (Html.BeginForm("Create", "Service"))
{
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.Gender)
        @Html.DropDownListFor(c => c.Customer.GenderId, new SelectList(Model.Genders, "Id", "Name"), new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.FirstName)
        @Html.TextBoxFor(c => c.Customer.FirstName, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.LastName)
        @Html.TextBoxFor(c => c.Customer.LastName, new { @class = "form-control" })
    </div>
    <div class="form-group input-group-md">
        @Html.LabelFor(c => c.Customer.DateOfBirth)
        @Html.TextBoxFor(c => c.Customer.DateOfBirth, "   {0:d MMM yyyy}", new { @class = "form-control datepicker" })
        @Html.ValidationMessageFor(c => c.Customer.DateOfBirth)
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.IDNumber)
        @Html.TextBoxFor(c => c.Customer.IDNumber, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.PhoneNumber)
        @Html.TextBoxFor(c => c.Customer.PhoneNumber, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.EmailAddress)
        @Html.TextBoxFor(c => c.Customer.EmailAddress, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="/Service/Customers" class="btn btn-danger">Cancel</a>

}

@section Scripts{
    <script type="text/javascript">

        $('.datepicker').datepicker();

    </script>

}

HotelApplication/Views/Service/Reservations.cshtml
@model IEnumerable<HotelApplication.Models.Reservation>
@{
    ViewBag.Title = "Reservations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_ServiceNavBar")

<h2>Reservations</h2>

<hr />
<button onclick="location.href='@Url.Action("NewForm", "Reservation")'" class="btn btn-primary">Create Reservation</button>
<hr />

<table id="reservations" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Customer Details</th>
            <th>Room Details</th>
            <th>Status</th>
            <th>Payment</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

@section Scripts{
    <script>
        $(document).ready(function () {
            var table = $("#reservations").DataTable({
                ajax: {
                    url: "/api/Services/Reservations",
                    dataSrc: "",
                },

                columns: [
                    {
                        data: "id"
                    },
                    {
                        data: "customer",
                        render: function (data, type, reservation) {
                            var fullName= data.firstName+" "+data.lastName;
                            return "<a href='/Customer/CustomerDetails/" +reservation.customerId+"'>"+fullName+"</a>"
                        }
                    },
                    {
                        data: "room",
                        render: function (data, type, reservation) {
                            return "<a href='/Room/RoomDetails/"+reservation.roomId+"'>"+reservation.roomId+"</a>"
                        }
                    },
                    {
                        data: "rStatus",
                        render: function (data) {
                            return " " + data.name;
                        }
                    },
                    {
                        data:"id",
                    },
                    {
                        data: "id",
                        render: function (data,type,reservation) {
                            var confirmBtn = "<button class='btn btn-success js-confirm' data-reservation-id='"+ data+ "' data-status='confirm'>Confirm</button>";
                            var cancelBtn = "<button class='btn btn-warning js-cancel' data-reservation-id='" + data + "'data-status='cancel'>Cancel</button>";
                            var deleteBtn = "<button class='btn btn-danger js-delete' data-reservation-id=" + data + ">Delete</button>";
                            return confirmBtn + cancelBtn + deleteBtn;
                        }
                    }
                ]
            })
            $("#reservations").on("click", ".js-delete", function () {
                var button = $(this);

                bootbox.confirm("Are you sure you want to delete this reservation?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/Services/Reservations/" + button.attr("data-reservation-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }
                        })
                    }
                });
            });

            $("#reservations").on("click", ".js-cancel", function () {
                var button = $(this);

                bootbox.confirm("Do you want to cancel this reservation?", function (result) {
                    if (result) {

                        $.ajax({
                            url: "/api/Services/Reservations/Status/" + button.attr("data-reservation-id") + "," + button.attr("data-status"),
                            method: "PUT",
                            success: function () {
                                table.ajax.reload();
                            }
                        })
                    }
                });
            });

            $("#reservations").on("click", ".js-confirm", function () {
                var button = $(this);

                bootbox.confirm("Do you want to confirm this reservation?", function (result) {
                    if (result) {

                        $.ajax({
                            url: "/api/Services/Reservations/Status/" + button.attr("data-reservation-id") + "," + button.attr("data-status"),
                            method: "PUT",
                            success: function () {
                                table.ajax.reload();
                            }
                        })
                    }
                });
            });
        })



    </script>
}

HotelApplication/Views/Service/Rooms.cshtml
@model IEnumerable<HotelApplication.Models.Room>
@{
    ViewBag.Title = "Rooms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_ServiceNavBar")

<h2>Rooms</h2>

<hr />
<hr />

<!---  SMALL ROOMS-->
<h3>Small Rooms</h3>
<table id="smRooms" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Room Number</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<!---  MEDIUM ROOMS-->
<h3>Medium Rooms</h3>
<table id="mdRooms" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Room Number</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<!---  LARGE ROOMS-->
<h3>Large Rooms</h3>
<table id="lgRooms" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Room Number</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

@section scripts{
    <script>
        var tableRender = {
            Sm: RenderTable("#smRooms"),
            Md: RenderTable("#mdRooms"),
            Lg: RenderTable("#lgRooms")
        }
        $(document).ready(tableRender.Sm,tableRender.Md,tableRender.Lg);

        function RenderTable(table) {
            var roomSize = table==="#smRooms"?1:(table==="#mdRooms"?2:3)
            $(table).DataTable({
                ajax: {
                    url: "/api/Services/Rooms",
                    dataSrc: function (json) {
                        return json.filter(c=> c.roomTypeId === roomSize);
                        //return json.slice(0,20);
                    },
                },

                columns: [
                    {
                        data: "id"
                    },
                    {
                        data: "roomStatus",
                        render: function (data) {
                            return " " + data.name;
                        }
                    },
                {
                    data: "id",
                    render: function (data) {
                        return "<a href='/Room/RoomDetails/" + data + "' class='btn btn-primary' data-customer-id= >View Details</a>";

                        /* return "<button class='btn btn-primary'>View Details</button>" */
                    }
                }
                ]
            });
        }
    </script>
}